	// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc5137.JavaCode2015RB.subsystems;

import org.usfirst.frc5137.JavaCode2015RB.RobotMap;
import org.usfirst.frc5137.JavaCode2015RB.commands.*;
import edu.wpi.first.wpilibj.*;
import org.usfirst.frc5137.JavaCode2015RB.TwistSteerDrive;

import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class DriveBase extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    SpeedController leftMotor = RobotMap.driveBaseLeftMotor;
    SpeedController rightMotor = RobotMap.driveBaseRightMotor;
    // RobotDrive chassis = RobotMap.driveBasechassis;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    TwistSteerDrive chassis = RobotMap.driveBasechassis;

    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void takeJoystickInput(Joystick driveStick){
    	// chassis.arcadeDrive(driveStick);
    	chassis.twistDrive(driveStick, true);
    }
    public void stop(){
    	chassis.drive(0,  0);
    }
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
        setDefaultCommand(new Drive());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }
}

