// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc5137.JavaCode2015RB.commands;
import edu.wpi.first.wpilibj.command.CommandGroup;

/**
 *
 */
public class Autonomous extends CommandGroup {
    
    public  Autonomous() {
    	addSequential(new DriveSidewaysAuto(-0.75, 3.5));
    	addSequential(new DriveSidewaysAuto(0.5, 1.5));
    	addSequential(new PneumaticExtendAuto());
    	addSequential(new DriveAuto(0.5, 0, 1.0));
    	addSequential(new PneumaticRetractAuto());
    	addSequential(new RaiseElevatorAuto(0.5));
    	addSequential(new DriveAuto(-0.5, 0, 0.5));
    	addSequential(new DriveAuto(-0.3, 0.5, 1.5));
    	addSequential(new DriveAuto(0.5, 0, 2));
        // Add Commands here:
        // e.g. addSequential(new Command1());
        //      addSequential(new Command2());
        // these will run in order.

        // To run multiple commands at the same time,
        // use addParallel()
        // e.g. addParallel(new Command1());
        //      addSequential(new Command2());
        // Command1 and Command2 will run in parallel.

        // A command group will require all of the subsystems that each member
        // would require.
        // e.g. if Command1 requires chassis, and Command2 requires arm,
        // a CommandGroup containing them would require both the chassis and the
        // arm.
    }
}
